<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SONY-PC" ignored="0" name="Login Test" tests="2" failures="1" timestamp="25 Mar 2020 06:58:01 GMT" time="68.966" errors="0">
  <testcase name="titleTest" time="0.031" classname="fmaven.mymaveen.Login">
    <failure type="java.lang.AssertionError" message="expected [Google] but found [Zoho - Cloud Software Suite and SaaS Applications for Businesses]">
      <![CDATA[java.lang.AssertionError: expected [Google] but found [Zoho - Cloud Software Suite and SaaS Applications for Businesses]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at fmaven.mymaveen.Login.titleTest(Login.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- titleTest -->
  <testcase name="test1" time="3.944" classname="fmaven.mymaveen.Login"/>
</testsuite> <!-- Login Test -->
